// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38Sd1BJuxiGD61c0HWuWfHWwqnJU03C0',
    appId: '1:7717666132:web:95edf9c3cc4334d9119cc1',
    messagingSenderId: '7717666132',
    projectId: 'renconsport',
    authDomain: 'renconsport.firebaseapp.com',
    storageBucket: 'renconsport.appspot.com',
    measurementId: 'G-G9C14QFPT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzM4bGZNDo8TMqXI5o9wyYg9oy2TmaoNQ',
    appId: '1:7717666132:android:e64fac3337e823b3119cc1',
    messagingSenderId: '7717666132',
    projectId: 'renconsport',
    storageBucket: 'renconsport.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDw46rTPaqVots-OkWpBf93bM04lZdFA',
    appId: '1:7717666132:ios:b26e426205537547119cc1',
    messagingSenderId: '7717666132',
    projectId: 'renconsport',
    storageBucket: 'renconsport.appspot.com',
    iosClientId:
        '7717666132-48rrjhi952ti20c7ebp6tpodbhp7t40p.apps.googleusercontent.com',
    iosBundleId: 'com.example.renconsport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDw46rTPaqVots-OkWpBf93bM04lZdFA',
    appId: '1:7717666132:ios:aec9457722cafe27119cc1',
    messagingSenderId: '7717666132',
    projectId: 'renconsport',
    storageBucket: 'renconsport.appspot.com',
    iosClientId:
        '7717666132-44r1gmqd2h726hsjn3iok40rq0k94uhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.renconsport.RunnerTests',
  );
}
